# Generated by Django 5.1.7 on 2025-03-23 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='created_at',
            new_name='requested_at',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='dropoff_address',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='requested_by',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='description',
            field=models.TextField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
