# Generated by Django 5.1.7 on 2025-03-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_created_at_servicerequest_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='dropoff_location',
            field=models.CharField(default='123 Sesame st', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='pickup_location',
            field=models.CharField(default='123 Sesame st', max_length=255),
            preserve_default=False,
        ),
    ]
