# Generated by Django 5.1.7 on 2025-03-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_servicerequest_dropoff_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('concierge', 'Concierge'), ('dealer', 'Dealer'), ('owner', 'Owner')], default='customer', max_length=20, null=True),
        ),
    ]
