# Generated by Django 5.1.7 on 2025-03-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In service', 'In service'), ('Delivery', 'Delivery')], default='Pending', max_length=20),
        ),
    ]
