# Generated by Django 5.1.7 on 2025-03-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_user_options_alter_car_model_alter_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='job_type',
            field=models.CharField(choices=[('Car Wash', 'Car Wash'), ('Oil Change', 'Oil Change'), ('Engine Light', 'Engine Light'), ('Brake Pad Replacement', 'Brake Pad Replacement'), ('Battery Replacement', 'Battery Replacement'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
