# Generated by Django 5.1.7 on 2025-03-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Waiting for Payment', 'Waiting for Payment'), ('Pending', 'Pending'), ('In service', 'In service'), ('Delivery', 'Delivery'), ('Complete', 'Complete')], default='Waiting for Payment', max_length=20),
        ),
    ]
