# Generated by Django 5.1.7 on 2025-03-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
