# Generated by Django 5.1.7 on 2025-03-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_servicerequest_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('car_specialty', models.CharField(blank=True, max_length=255, null=True)),
                ('job_specialty', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
