# Generated by Django 5.1.7 on 2025-03-31 18:50

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='job_specialty',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Car Wash', 'Car Wash'), ('Oil Change', 'Oil Change'), ('Engine Light', 'Engine Light'), ('Brake Pad Replacement', 'Brake Pad Replacement'), ('Battery Replacement', 'Battery Replacement'), ('Other', 'Other')], max_length=80, null=True),
        ),
    ]
