# Generated by Django 5.1.7 on 2025-03-31 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_invoice1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice1',
            name='user',
        ),
        migrations.AddField(
            model_name='invoice1',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.servicerequest'),
        ),
        migrations.AlterField(
            model_name='invoice1',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice1',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
