# Generated by Django 5.1.7 on 2025-03-31 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_invoice1_user_invoice1_service_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice1',
            name='invoice_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice1',
            name='job_type',
            field=models.CharField(choices=[('Car Wash', 'Car Wash'), ('Oil Change', 'Oil Change'), ('Engine Light', 'Engine Light'), ('Brake Pad Replacement', 'Brake Pad Replacement'), ('Battery Replacement', 'Battery Replacement'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
