# Generated by Django 5.1.7 on 2025-03-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_invoice1_invoice_date_invoice1_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice1',
            name='job_type',
        ),
        migrations.AddField(
            model_name='invoice1',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice1',
            name='invoice_date',
            field=models.DateTimeField(),
        ),
    ]
