# Generated by Django 5.1.7 on 2025-03-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_invoice1_job_type_invoice1_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice1',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'Euro'), ('GEL', 'GEL')], default='GEL', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoice1',
            name='price',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
