# Generated by Django 5.1.7 on 2025-04-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_invoice1_currency_alter_invoice1_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice1',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=10),
        ),
    ]
