# Generated by Django 5.1.7 on 2025-04-01 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_invoice1_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('invoice_date', models.DateTimeField()),
                ('price', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'Euro'), ('GEL', 'GEL')], default='GEL', max_length=3)),
                ('payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=10)),
                ('dealer_address', models.TextField(blank=True, null=True)),
                ('dealer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('dealer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.dealer')),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.servicerequest')),
            ],
        ),
    ]
