# Generated by Django 5.1.7 on 2025-04-01 18:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_invoice2'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='assigned_dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='main.dealer'),
        ),
        migrations.AlterField(
            model_name='invoice1',
            name='invoice_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice2',
            name='dealer_address',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice2',
            name='dealer_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice2',
            name='dealer_phone',
            field=models.CharField(blank=True, default='unknown', max_length=20),
            preserve_default=False,
        ),
    ]
