# Generated by Django 5.1.7 on 2025-04-03 06:13

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_servicerequest_assigned_dealer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=20, unique=True, validators=[main.validators.validate_license_plate_format]),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100),
        ),
    ]
