# Generated by Django 5.1.7 on 2025-04-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_dealer_user_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='car_specialty',
        ),
        migrations.AddField(
            model_name='invoice1',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='invoice2',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
