# Generated by Django 5.1.7 on 2025-04-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_dealer_car_specialty_invoice1_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice1',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice2',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
