# Generated by Django 5.1.7 on 2025-04-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_invoice1_updated_at_alter_invoice2_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='concierge_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='concierge_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='share_location',
            field=models.BooleanField(default=False),
        ),
    ]
